version: '2'

services:
  app:
    image: 'discountsm:latest'
    build:
      context: .
    container_name: discountsm
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/discountsm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=discountsm
    ports:
      - "8080:8080"
  db:
    image: 'postgres:14.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=discountsm
      - POSTGRES_DB=discountsm
    ports:
      - "5432:5432"