version: '2'

services:
  app:
    image: 'discountsm:latest'
    build:
      context: .
    container_name: discountsm
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/circle_test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=
  db:
    image: 'postgres:14.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker_compose
      - POSTGRES_DB=discountsm