version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.1
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/discountsm
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: circle_ci
          POSTGRES_DB: discountsm
    steps:
      - checkout
      - run:
          name: Build
          command: mvn test verify

workflows:
  integration:
    jobs:
      - test
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          repo: discountsm
          tag: 'latest,discountsm'
