version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B compile
  test:
    docker:
      - image: cimg/openjdk:17.0.1
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/discountsm
      - image: cimg/postgres:14.0.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: circle_ci
          POSTGRES_DB: discountsm
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B verify

workflows:
  example:
    jobs:
      - build-and-test
